### ISSUE TITLE
https 상태에서 결제창이 열리지 않는 문제

### ISSUE THREAD

**Issue by ned3y2k** [gnuboard/youngcart5#3]
mobile/shop/lg/xpay_approval.php:139
http://xpay.uplus.co.kr/xpay/js/xpay_crossplatform.js
를
//xpay.uplus.co.kr/xpay/js/xpay_crossplatform.js로 교체 부탁드립니다.

**Comment by thisgun** [comment]
알려주셔서 감사합니다.

해당 부분을 수정하겠습니다.
