### ISSUE TITLE
이메일인증 시 1회 인증된 메일은 탈퇴 후 재가입 하더라도 메일인증을 안거치네요.

### ISSUE THREAD

**Issue by quroom** [gnuboard/youngcart5#5]
내부 코드를 살펴보는 중인데 찾을 수 없어서 이슈로 남깁니다.
mb_email_certify 값이 어디서 초기화되고 입력되는걸까요??

bbs\register.php 쪽인줄 알았는데 그쪽은 아니고
bbs\register_form_update.php 이쪽도 아니네요.

어느쪽을 살펴봐야 알 수 있을까요?

**Comment by thisgun** [comment]
안녕하세요.

해당 이슈에 대한 내용은 영카트 5에 없는 내용입니다.

탈퇴를 처리하는 파일은

bbs/member_leave.php 입니다.

코드를 보면 회원정보는 그대로 두고 탈퇴일만 업데이트 합니다.

그러므로 탈퇴된 메일은 다시 재가입을 할수가 없습니다. ( 이미 회원 테이블에 있기 때문에 )

코드를 수정해서 사용하거나, 다른 빌더들을 사용 하는지 확인해 보세요.
