### ISSUE TITLE
주문서 비밀번호 누락 위험성

### ISSUE THREAD

**Issue by ckcks12** [gnuboard/youngcart5#8]
/shop/orderformupdate.php:474

```php
if ($is_member)
    $od_pwd = $member['mb_password'];
else
    $od_pwd = get_encrypt_string($_POST['od_pwd']);
```

server-side $od_pwd validation 필요합니다.
8자 이하일경우 sql_password() 로 암호화 불가능하여 공백 반환됩니다.

**Comment by thisgun** [comment]
서버에서 mysql password 를 8자리 이하도 받을수 있게 설정을 변경해야 합니다.

아래 URL 을 보시고 변경해서 사용해 주세요.

https://kamang-it.tistory.com/entry/MySQL%ED%8C%A8%EC%8A%A4%EC%9B%8C%EB%93%9C-%EC%A0%95%EC%B1%85-%ED%99%95%EC%9D%B8-%EB%B3%80%EA%B2%BD%ED%95%98%EA%B8%B0

다음 5.4 버전의 영카트부터는 기본 패스워드 저장 방식이 달라질 예정입니다.
