### ISSUE TITLE
uri.lib.php each() 함수

### ISSUE THREAD

**Issue by yuyake** [gnuboard/youngcart5#9]
while(list($k,$v) = each($s)) $return_url .= '/'.$v;

each 함수가 Deprecated 되어서 오류가 발생하는데 이대로 가는건가요?

**Comment by thisgun** [comment]
알려주셔서 감사합니다.

아래와 같이 수정하겠습니다.

https://github.com/gnuboard/gnuboard5/commit/a5e553147148fa17e93fea05c39dd0dadd34ccfc
